version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solblaze
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3 